/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as NearMeRouteImport } from './routes/near-me'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DealDealIdRouteImport } from './routes/deal.$dealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const NearMeRoute = NearMeRouteImport.update({
  id: '/near-me',
  path: '/near-me',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DealDealIdRoute = DealDealIdRouteImport.update({
  id: '/deal/$dealId',
  path: '/deal/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/near-me': typeof NearMeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/near-me': typeof NearMeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/near-me': typeof NearMeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/categories' | '/near-me' | '/saved' | '/search' | '/deal/$dealId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories' | '/near-me' | '/saved' | '/search' | '/deal/$dealId'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/near-me'
    | '/saved'
    | '/search'
    | '/deal/$dealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  NearMeRoute: typeof NearMeRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  DealDealIdRoute: typeof DealDealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/near-me': {
      id: '/near-me'
      path: '/near-me'
      fullPath: '/near-me'
      preLoaderRoute: typeof NearMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$dealId': {
      id: '/deal/$dealId'
      path: '/deal/$dealId'
      fullPath: '/deal/$dealId'
      preLoaderRoute: typeof DealDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  NearMeRoute: NearMeRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  DealDealIdRoute: DealDealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
